services:
    voicevox:
        build: ./voicevox
        restart: always
        ports:
            - '50021:50021'
        environment:
            - VOICEVOX_USER=user
        networks:
            - voicevox
    miku:
        build: .
        environment:
            - CLIENT_TOKEN=${CLIENT_TOKEN}
            - DB_DRIVER=${DB_DRIVER}
            - DB_HOST=${DB_HOST}
            - DB_TABLE=${DB_TABLE}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - VOIDS_API=${VOIDS_API}
            - VOICEVOX_API=${VOICEVOX_API}
            - ERROR_WH=${ERROR_WH}
            - SYSTEM_WH=${SYSTEM_WH}
            - ADDITIONAL_WH=${ADDITIONAL_WH}
            - ENCRYPTION_KEY=${ENCRYPTION_KEY}
            - APP_URL=${APP_URL}
        volumes:
            - ./logs:/usr/src/app/logs
        restart: always
        networks:
            - voicevox

networks:
    voicevox:
        driver: 'bridge'
