name: Create Pull Request

on:
    push:
        branches:
            - develop

jobs:
    create-pr:
        runs-on: ubuntu-latest
        steps:
            - name: リポジトリをチェックアウト
              uses: actions/checkout@v4

            - name: プルリクエストを作成
              uses: peter-evans/create-pull-request@v6
              with:
                  branch: develop
                  base: main
                  title: 'Develop を Main にマージ'
                  body: 'このプルリクエストは GitHub Actions によって自動作成されました。'
                  labels: '自動PR'
